### ISSUE TITLE
[1.12] TODO list for 1.12 udpate

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/Atomic-Science#45]
- [x] Configuration system
- [x] Mod info file
- [x] Rework network code
- [x] Add IC2 support
- [x] Add BC support
- [x] Add recipes
- [x] Add recipes for mods
- [x] Add is mod loaded conditional
- [x] Disable vanilla recipes if mods are loaded that can provide resources
- [x] Shift+Click for GUIs
- [x] Slot support for batteries and fluids
- [x] Slot validation to prevent wrong items in slots
- [x] Slot icons
- [x] Check if we need an upper limit on generator output
- [x] Check if we need a real output energy storage for generators
- [x] Fix reactor heat not decaying
- [ ] Add recipe for 238
- [x] Add recipe for the controller
- [x] GUI fluid render

Beta Release
- [x] Rework grid system to work with nodes
- [x] Have sources store node list for easy removal (could store as an array of chunk coords contain list of nodes per chunk)
- [x] Switch threads to path using source as the input
- [x] Have nodes set as dead if a source is invalid
- [x] Have chunks scan for dead sources and remove
- [x] Have chunks clean up data to reduce memory usage (remove empty layers & chunks)

- [x] Have map check for updates near sources to queue updates of sources
- [x] Rework grid system to use capabilities
- [x] Rework heat and radiation sources to use capabilities
